"""Add browser control plane and node security schema

Revision ID: 7f6769cf78ae
Revises: a12d98d77c31
Create Date: 2026-07-29 09:32:33.214017
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7f6769cf78ae"
down_revision: str | None = "a12d98d77c31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=False),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_organisation_id"), "audit_events", ["organisation_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_target_id"), "audit_events", ["target_id"], unique=False)
    op.create_table(
        "browser_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("csrf_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_from_id", sa.String(length=36), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["rotated_from_id"],
            ["browser_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_browser_sessions_expires_at"), "browser_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_browser_sessions_user_id"), "browser_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "organisation_memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organisation_id", "user_id"),
    )
    op.create_index(
        op.f("ix_organisation_memberships_organisation_id"),
        "organisation_memberships",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organisation_memberships_user_id"),
        "organisation_memberships",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "passkeys",
        sa.Column("id", sa.String(length=300), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("transports_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_passkeys_user_id"), "passkeys", ["user_id"], unique=False)
    op.create_table(
        "recovery_codes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recovery_codes_user_id"), "recovery_codes", ["user_id"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspaces_organisation_id"), "workspaces", ["organisation_id"], unique=False
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("key_id", sa.String(length=100), nullable=False),
        sa.Column("platform", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nodes_key_id"), "nodes", ["key_id"], unique=False)
    op.create_index(op.f("ix_nodes_organisation_id"), "nodes", ["organisation_id"], unique=False)
    op.create_index(op.f("ix_nodes_workspace_id"), "nodes", ["workspace_id"], unique=False)
    op.create_table(
        "pairing_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("user_code", sa.String(length=20), nullable=False),
        sa.Column("device_code_hash", sa.String(length=128), nullable=False),
        sa.Column("code_challenge", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by_user_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_code_hash"),
        sa.UniqueConstraint("user_code"),
    )
    op.create_index(
        op.f("ix_pairing_sessions_expires_at"), "pairing_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_pairing_sessions_organisation_id"),
        "pairing_sessions",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pairing_sessions_workspace_id"), "pairing_sessions", ["workspace_id"], unique=False
    )
    op.create_table(
        "routing_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("paid_route_policy", sa.String(length=30), nullable=False),
        sa.Column("limits_json", sa.Text(), nullable=False),
        sa.Column("fireconnect_enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_routing_policies_workspace_id"), "routing_policies", ["workspace_id"], unique=False
    )
    op.create_table(
        "action_plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("browser_session_id", sa.String(length=36), nullable=False),
        sa.Column("harness_id", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("risk", sa.String(length=30), nullable=False),
        sa.Column("plan_hash", sa.String(length=128), nullable=False),
        sa.Column("plan_json", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["browser_session_id"],
            ["browser_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_hash"),
    )
    op.create_index(
        op.f("ix_action_plans_expires_at"), "action_plans", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_action_plans_node_id"), "action_plans", ["node_id"], unique=False)
    op.create_table(
        "harness_installations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("harness_id", sa.String(length=100), nullable=False),
        sa.Column("executable", sa.Text(), nullable=True),
        sa.Column("version", sa.String(length=300), nullable=True),
        sa.Column("readiness", sa.String(length=50), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_harness_installations_harness_id"),
        "harness_installations",
        ["harness_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_harness_installations_node_id"), "harness_installations", ["node_id"], unique=False
    )
    op.create_index(
        op.f("ix_harness_installations_readiness"),
        "harness_installations",
        ["readiness"],
        unique=False,
    )
    op.create_table(
        "node_credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_node_credentials_node_id"), "node_credentials", ["node_id"], unique=False
    )
    op.create_table(
        "node_presence",
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("connection_id", sa.String(length=100), nullable=False),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("node_id"),
        sa.UniqueConstraint("connection_id"),
    )
    op.create_index(
        op.f("ix_node_presence_last_seen_at"), "node_presence", ["last_seen_at"], unique=False
    )
    op.create_table(
        "onboarding_progress",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=36), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("data_json", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_onboarding_progress_state"), "onboarding_progress", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_onboarding_progress_user_id"), "onboarding_progress", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_onboarding_progress_workspace_id"),
        "onboarding_progress",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "remote_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_context_id", sa.String(length=36), nullable=False),
        sa.Column("organisation_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("harness_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("nonce", sa.String(length=100), nullable=False),
        sa.Column("envelope_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nonce"),
    )
    op.create_index(op.f("ix_remote_tasks_node_id"), "remote_tasks", ["node_id"], unique=False)
    op.create_index(
        op.f("ix_remote_tasks_organisation_id"), "remote_tasks", ["organisation_id"], unique=False
    )
    op.create_index(op.f("ix_remote_tasks_status"), "remote_tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_remote_tasks_task_context_id"), "remote_tasks", ["task_context_id"], unique=False
    )
    op.create_index(
        op.f("ix_remote_tasks_workspace_id"), "remote_tasks", ["workspace_id"], unique=False
    )
    op.create_table(
        "workspace_grants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("root_path", sa.Text(), nullable=False),
        sa.Column("allow_read", sa.Boolean(), nullable=False),
        sa.Column("allow_write", sa.Boolean(), nullable=False),
        sa.Column("allow_shell", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspace_grants_node_id"), "workspace_grants", ["node_id"], unique=False
    )
    op.create_index(
        op.f("ix_workspace_grants_workspace_id"), "workspace_grants", ["workspace_id"], unique=False
    )
    op.create_table(
        "control_plane_approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("browser_session_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("plan_hash", sa.String(length=128), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["browser_session_id"],
            ["browser_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["action_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_plane_approvals_plan_id"),
        "control_plane_approvals",
        ["plan_id"],
        unique=False,
    )
    op.create_table(
        "harness_account_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("funding_kind", sa.String(length=50), nullable=False),
        sa.Column("billing_mode", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.String(length=30), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["harness_installations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_harness_account_states_installation_id"),
        "harness_account_states",
        ["installation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_harness_account_states_installation_id"), table_name="harness_account_states"
    )
    op.drop_table("harness_account_states")
    op.drop_index(op.f("ix_control_plane_approvals_plan_id"), table_name="control_plane_approvals")
    op.drop_table("control_plane_approvals")
    op.drop_index(op.f("ix_workspace_grants_workspace_id"), table_name="workspace_grants")
    op.drop_index(op.f("ix_workspace_grants_node_id"), table_name="workspace_grants")
    op.drop_table("workspace_grants")
    op.drop_index(op.f("ix_remote_tasks_workspace_id"), table_name="remote_tasks")
    op.drop_index(op.f("ix_remote_tasks_task_context_id"), table_name="remote_tasks")
    op.drop_index(op.f("ix_remote_tasks_status"), table_name="remote_tasks")
    op.drop_index(op.f("ix_remote_tasks_organisation_id"), table_name="remote_tasks")
    op.drop_index(op.f("ix_remote_tasks_node_id"), table_name="remote_tasks")
    op.drop_table("remote_tasks")
    op.drop_index(op.f("ix_onboarding_progress_workspace_id"), table_name="onboarding_progress")
    op.drop_index(op.f("ix_onboarding_progress_user_id"), table_name="onboarding_progress")
    op.drop_index(op.f("ix_onboarding_progress_state"), table_name="onboarding_progress")
    op.drop_table("onboarding_progress")
    op.drop_index(op.f("ix_node_presence_last_seen_at"), table_name="node_presence")
    op.drop_table("node_presence")
    op.drop_index(op.f("ix_node_credentials_node_id"), table_name="node_credentials")
    op.drop_table("node_credentials")
    op.drop_index(op.f("ix_harness_installations_readiness"), table_name="harness_installations")
    op.drop_index(op.f("ix_harness_installations_node_id"), table_name="harness_installations")
    op.drop_index(op.f("ix_harness_installations_harness_id"), table_name="harness_installations")
    op.drop_table("harness_installations")
    op.drop_index(op.f("ix_action_plans_node_id"), table_name="action_plans")
    op.drop_index(op.f("ix_action_plans_expires_at"), table_name="action_plans")
    op.drop_table("action_plans")
    op.drop_index(op.f("ix_routing_policies_workspace_id"), table_name="routing_policies")
    op.drop_table("routing_policies")
    op.drop_index(op.f("ix_pairing_sessions_workspace_id"), table_name="pairing_sessions")
    op.drop_index(op.f("ix_pairing_sessions_organisation_id"), table_name="pairing_sessions")
    op.drop_index(op.f("ix_pairing_sessions_expires_at"), table_name="pairing_sessions")
    op.drop_table("pairing_sessions")
    op.drop_index(op.f("ix_nodes_workspace_id"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_organisation_id"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_key_id"), table_name="nodes")
    op.drop_table("nodes")
    op.drop_index(op.f("ix_workspaces_organisation_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_recovery_codes_user_id"), table_name="recovery_codes")
    op.drop_table("recovery_codes")
    op.drop_index(op.f("ix_passkeys_user_id"), table_name="passkeys")
    op.drop_table("passkeys")
    op.drop_index(
        op.f("ix_organisation_memberships_user_id"), table_name="organisation_memberships"
    )
    op.drop_index(
        op.f("ix_organisation_memberships_organisation_id"), table_name="organisation_memberships"
    )
    op.drop_table("organisation_memberships")
    op.drop_index(op.f("ix_browser_sessions_user_id"), table_name="browser_sessions")
    op.drop_index(op.f("ix_browser_sessions_expires_at"), table_name="browser_sessions")
    op.drop_table("browser_sessions")
    op.drop_index(op.f("ix_audit_events_target_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_organisation_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("organisations")
    # ### end Alembic commands ###
